### ISSUE TITLE
consider additional OB fields

### ISSUE THREAD

**Issue by jeffvance** [yard-turkey/lib-bucket-provisioner#55]
From the original design doc:
```
spec:
  SSL: true | false [6]       # post phase-0, if at all
  cannedBucketACL: [7]        # post phase-0, if at all
  versioned: true | false [8] # post phase-0, if at all
```
