### ISSUE TITLE
verify that Status.Phase is set and works per design

### ISSUE THREAD

**Issue by jeffvance** [yard-turkey/lib-bucket-provisioner#56]
From the doc:
```
status:
  phase: {"pending", "bound", "released", "failed"}  [5]
...
1. phases of bucket creation, mutually exclusive:
    - _pending_: the operator is processing the request
    - _bound_: the operator finished processing the request and linked the OBC and OB
    - _released_: the OB has been deleted, leaving the OBC unclaimed but unavailable.
```
